/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Brawan
 */
public class CurrLattes extends javax.swing.JFrame {
    File dir = null;
    int ano = 0 ;
       /**
     * Creates new form CurrLattes
     */
    public CurrLattes() throws IOException {        
        initComponents();
        translate();
        setImages();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.as
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        pTable = new javax.swing.JButton();
        pSearch = new javax.swing.JButton();
        pVisual = new javax.swing.JButton();
        pBancoDados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pMenuBar = new javax.swing.JMenuBar();
        pArq = new javax.swing.JMenu();
        pAtualizaBD = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        pPref = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        pSair = new javax.swing.JMenuItem();
        pOpc = new javax.swing.JMenu();
        pLang = new javax.swing.JMenu();
        pLPort = new javax.swing.JRadioButtonMenuItem();
        pLEng = new javax.swing.JRadioButtonMenuItem();
        pBD = new javax.swing.JMenu();
        pAbout = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("+Produção");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pTable.setToolTipText("Gerar Planilha");
        pTable.setMaximumSize(new java.awt.Dimension(85, 49));
        pTable.setMinimumSize(new java.awt.Dimension(85, 49));
        pTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTableMouseClicked(evt);
            }
        });

        pSearch.setToolTipText("Pesquisar");
        pSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pSearch.setMaximumSize(new java.awt.Dimension(85, 49));
        pSearch.setMinimumSize(new java.awt.Dimension(85, 49));
        pSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSearchMouseClicked(evt);
            }
        });
        pSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pSearchActionPerformed(evt);
            }
        });

        pVisual.setToolTipText("Gerar Visualização");
        pVisual.setMaximumSize(new java.awt.Dimension(86, 49));
        pVisual.setMinimumSize(new java.awt.Dimension(85, 49));
        pVisual.setPreferredSize(new java.awt.Dimension(84, 46));
        pVisual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pVisualMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pVisualMouseClicked(evt);
            }
        });
        pVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pVisualActionPerformed(evt);
            }
        });

        pBancoDados.setToolTipText("Banco de Dados");
        pBancoDados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pBancoDados.setMaximumSize(new java.awt.Dimension(85, 49));
        pBancoDados.setMinimumSize(new java.awt.Dimension(85, 49));
        pBancoDados.setName(""); // NOI18N
        pBancoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pBancoDadosActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(5, 21));

        jLabel1.setText("Ultima Atualização 09/05/2014");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pArq.setText("Arquivo");
        pArq.setPreferredSize(new java.awt.Dimension(57, 25));

        pAtualizaBD.setText("Atualizar BD");
        pAtualizaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAtualizaBDActionPerformed(evt);
            }
        });
        pArq.add(pAtualizaBD);
        pArq.add(jSeparator1);

        pPref.setText("Preferências");
        pPref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPrefActionPerformed(evt);
            }
        });
        pArq.add(pPref);
        pArq.add(jSeparator2);

        pSair.setText("Sair");
        pSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pSairActionPerformed(evt);
            }
        });
        pArq.add(pSair);

        pMenuBar.add(pArq);

        pOpc.setText("Opções");

        pLang.setText("Linguagem");

        pLPort.setSelected(true);
        pLPort.setText("Português");
        pLPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pLPortActionPerformed(evt);
            }
        });
        pLang.add(pLPort);

        pLEng.setSelected(true);
        pLEng.setText("English");
        pLEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pLEngActionPerformed(evt);
            }
        });
        pLang.add(pLEng);

        pOpc.add(pLang);

        pMenuBar.add(pOpc);

        pBD.setText("Ajuda");
        pBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pBDActionPerformed(evt);
            }
        });

        pAbout.setText("Sobre");
        pAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAboutActionPerformed(evt);
            }
        });
        pBD.add(pAbout);

        pMenuBar.add(pBD);

        setJMenuBar(pMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pBancoDados, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pTable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBancoDados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pTable, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(pVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleDescription("+Produção");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSearchMouseClicked
      Search busca = null;
      try {
        busca = new Search();
      } catch (FileNotFoundException ex) {
        Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
        Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
      }
        busca.setVisible(true);
    }//GEN-LAST:event_pSearchMouseClicked

    private void pVisualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pVisualMouseClicked
     try {
       Visual init = new Visual();
     } catch (IOException ex) {
         Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
     }  
    }//GEN-LAST:event_pVisualMouseClicked

    private void pPrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPrefActionPerformed
    Preferencias pref = null;
    try {
      pref = new Preferencias(false);
    } catch (FileNotFoundException ex) {
      Logger.getLogger(InterfaceBD.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
      Logger.getLogger(InterfaceBD.class.getName()).log(Level.SEVERE, null, ex);
    }
    pref.setVisible(true);
    }//GEN-LAST:event_pPrefActionPerformed

    private void pAtualizaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAtualizaBDActionPerformed
     
       jFileChooser1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
       int opcao = jFileChooser1.showOpenDialog(this);
      
       if (opcao == JFileChooser.APPROVE_OPTION){
        dir = jFileChooser1.getSelectedFile();
       }
                  
       if(dir!= null){  
            try {               
               UpdateBD init = new UpdateBD(dir.getAbsolutePath(),true);
           } catch (IOException ex) {
               Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
           } catch (InterruptedException ex) {
               Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
           } catch (Exception ex) {   
           Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
         }   
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_pAtualizaBDActionPerformed

    private void pTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTableMouseClicked
      GerarPlanilha plan = null;
      try {
        plan = new GerarPlanilha();
      } catch (FileNotFoundException ex) {
        Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
        Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
      }
        plan.setVisible(true);
    }//GEN-LAST:event_pTableMouseClicked

    private void pSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pSairActionPerformed
     System.exit(1);
    }//GEN-LAST:event_pSairActionPerformed

private void pVisualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pVisualMouseEntered
   
}//GEN-LAST:event_pVisualMouseEntered

    private void pVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pVisualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pVisualActionPerformed

    private void pSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pSearchActionPerformed

    private void pLPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pLPortActionPerformed
      if(pLPort.isSelected()){
           pLEng.setSelected(false);
      }
      pLPort.setSelected(true);
      utilsIO.write("locale.txt","pt_BR");
      try {
        translate();
      } catch (Exception e) {
        Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, e);
      }
       
       
    }//GEN-LAST:event_pLPortActionPerformed

    private void pLEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pLEngActionPerformed

      if(pLEng.isSelected()){
           pLPort.setSelected(false);
      }
      pLEng.setSelected(true);
      
      utilsIO.write("locale.txt","en_US");
      try {
        translate();
      } catch (Exception e) {
        Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, e);
      }
      
    }//GEN-LAST:event_pLEngActionPerformed

  private void pBancoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBancoDadosActionPerformed
    InterfaceBD banco = null;
      try {
        banco = new InterfaceBD();
      } catch (SQLException ex) {
        Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
      } catch (FileNotFoundException ex) {
        Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
        Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
      }
    banco.setVisible(true);
  }//GEN-LAST:event_pBancoDadosActionPerformed

  private void pBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBDActionPerformed

  }//GEN-LAST:event_pBDActionPerformed

  private void pAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAboutActionPerformed
       try{
      About ab = new About();
      ab.setVisible(true);
    }catch(Exception e){
      System.out.print(e.toString());
    }
  }//GEN-LAST:event_pAboutActionPerformed
  
    private void saveLocale(int local){
    try {
      FileWriter fstream = null;
      fstream = new FileWriter("locale.txt"); //WRITE
      BufferedWriter out = new BufferedWriter(fstream); 

      out.write(""+local);
      out.close();

    } catch (IOException ex) {
        Logger.getLogger(Preferencias.class.getName()).log(Level.SEVERE, null, ex);
    }
  }
  
  public void setImages(){
    
    /// Set the Buttons Images

    Image help = (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Search.png")));
    ImageIcon search = new ImageIcon(help);

    help = (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/tableIcon.png")));
    ImageIcon planilha = new ImageIcon(help);

    help = (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/parallel.png")));
    ImageIcon visual = new ImageIcon(help);

    help = (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/dbIcon.png")));
    ImageIcon bdIcon = new ImageIcon(help);

    pSearch.setIcon(search);
    pTable.setIcon(planilha);
    pVisual.setIcon(visual);
    pBancoDados.setIcon(bdIcon);
  
  }
  
  public void translate() throws FileNotFoundException, IOException{
    Vector<String> lang = utilsIO.getTranslate("pFile pPref pAtualizaBD pExit pOpt pAbout pLang pSearch pTable pVisual pBancoDados");
  
    pArq.setText(lang.get(0));
    pPref.setText(lang.get(1));
    pAtualizaBD.setText(lang.get(2));
    pSair.setText(lang.get(3));

    pOpc.setText(lang.get(4));
    pAbout.setText(lang.get(5));
    pLang.setText(lang.get(6));

    pSearch.setToolTipText(lang.get(7));
    pTable.setToolTipText(lang.get(8));
    pVisual.setToolTipText(lang.get(9));
    pBancoDados.setToolTipText(lang.get(10));
    
    if(utilsIO.read("locale.txt").equals("pt_BR")){
        pLPort.setSelected(true);
        pLEng.setSelected(false);
    }
    else{
        pLPort.setSelected(false);
        pLEng.setSelected(true);
    }
    
  
  }
      
  
  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			System.out.println(info.getName());
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrLattes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrLattes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrLattes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrLattes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              try {
                new CurrLattes().setVisible(true);
              } catch (IOException ex) {
                Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
              }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem pAbout;
    private javax.swing.JMenu pArq;
    private javax.swing.JMenuItem pAtualizaBD;
    private javax.swing.JMenu pBD;
    private javax.swing.JButton pBancoDados;
    private javax.swing.JRadioButtonMenuItem pLEng;
    private javax.swing.JRadioButtonMenuItem pLPort;
    private javax.swing.JMenu pLang;
    private javax.swing.JMenuBar pMenuBar;
    private javax.swing.JMenu pOpc;
    private javax.swing.JMenuItem pPref;
    private javax.swing.JMenuItem pSair;
    private javax.swing.JButton pSearch;
    private javax.swing.JButton pTable;
    private javax.swing.JButton pVisual;
    // End of variables declaration//GEN-END:variables
}
