/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Brawan
 */
public class GerarPlanilha extends javax.swing.JFrame {
    
    int bAno = -1 , eAno = 999999;
    
    /**
     * Creates new form GerarPlanilha
     */
    public GerarPlanilha() throws FileNotFoundException, IOException {
        initComponents();
        translate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    beginYear = new javax.swing.JTextField();
    gYear = new javax.swing.JLabel();
    gCreate = new javax.swing.JButton();
    gCancel = new javax.swing.JButton();
    endYear = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();

    setTitle("Planilha");

    beginYear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        beginYearActionPerformed(evt);
      }
    });

    gYear.setFont(new java.awt.Font("Calibri", 3, 16)); // NOI18N
    gYear.setText("ANO");

    gCreate.setText("Criar");
    gCreate.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        gCreateMouseClicked(evt);
      }
    });

    gCancel.setText("Cancelar");
    gCancel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        gCancelMouseClicked(evt);
      }
    });

    endYear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        endYearActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
    jLabel2.setText("-");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(110, 110, 110)
        .addComponent(gYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(gCreate)
            .addGap(39, 39, 39)
            .addComponent(gCancel))
          .addGroup(layout.createSequentialGroup()
            .addGap(44, 44, 44)
            .addComponent(beginYear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(endYear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(35, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(gYear)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(beginYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(endYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(48, 48, 48)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(gCancel)
          .addComponent(gCreate))
        .addContainerGap(22, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void beginYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginYearActionPerformed
        bAno =  Integer.parseInt(beginYear.getText());
    }//GEN-LAST:event_beginYearActionPerformed

    private void gCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gCreateMouseClicked

      if(beginYear.getText().length() > 0)
        bAno =  Integer.parseInt(beginYear.getText());
      if(endYear.getText().length() > 0)
        eAno = Integer.parseInt(endYear.getText());
      try {
        BuildPlanilha init = new BuildPlanilha(bAno,eAno);
      } catch (IOException ex) {
        Logger.getLogger(GerarPlanilha.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
        Logger.getLogger(GerarPlanilha.class.getName()).log(Level.SEVERE, null, ex);
      }

        setVisible(false);
    }//GEN-LAST:event_gCreateMouseClicked

    private void gCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gCancelMouseClicked
        setVisible(false);
    }//GEN-LAST:event_gCancelMouseClicked

  private void endYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endYearActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_endYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarPlanilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarPlanilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarPlanilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarPlanilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              try {
                new GerarPlanilha().setVisible(true);
              } catch (FileNotFoundException ex) {
                Logger.getLogger(GerarPlanilha.class.getName()).log(Level.SEVERE, null, ex);
              } catch (IOException ex) {
                Logger.getLogger(GerarPlanilha.class.getName()).log(Level.SEVERE, null, ex);
              }
            }
        });
    }
    public void translate() throws FileNotFoundException, IOException{
      Locale currentLocale;
      ResourceBundle messages;

      BufferedReader br = null;                   // READ
      String sCurrentLine;
      String local = "";
      int i = 0;


      br = new BufferedReader(new FileReader("locale.txt"));            //// start copy first part of Index
      while ((sCurrentLine = br.readLine()) != null) {
            local = sCurrentLine;  
      }

      if(local.equals("en_US"))
        currentLocale = new Locale("en","US");
      else
        currentLocale = new Locale("pt","BR");

      messages = ResourceBundle.getBundle("locales.MessagesBundle",currentLocale);
  
      gCreate.setText(messages.getString("gCreate"));
      gCancel.setText(messages.getString("gCancel"));
      gYear.setText(messages.getString("gYear"));
      this.setTitle(messages.getString("gTitle"));
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField beginYear;
  private javax.swing.JTextField endYear;
  private javax.swing.JButton gCancel;
  private javax.swing.JButton gCreate;
  private javax.swing.JLabel gYear;
  private javax.swing.JLabel jLabel2;
  // End of variables declaration//GEN-END:variables
}
