/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import dataCon.DataBase;
import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Brawan
 */
public class Preferencias extends javax.swing.JFrame{
    boolean flag = false; 
    String ip = "";
    String login= "";
    String senha = "";
    String name = "";
    int bd = 0;
    File dir = null;
    
    /*
     * Creates new form Preferencias
     */
    public Preferencias() throws FileNotFoundException, IOException {
         initComponents();
         translate();

          flag = false;
          initComponents();
          translate();
          loadLoc();
          loadRem();

    }
    public Preferencias(boolean criar) throws FileNotFoundException, IOException {
        flag = criar;
        initComponents();
        translate();
        loadLoc();
        loadRem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        opPassLoc = new javax.swing.JLabel();
        ipField = new javax.swing.JTextField();
        opIPLoc = new javax.swing.JLabel();
        opUserLoc = new javax.swing.JLabel();
        opSaveLoc = new javax.swing.JButton();
        loginField = new javax.swing.JTextField();
        senhaField = new javax.swing.JTextField();
        opNameLoc = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        opBDLoc = new javax.swing.JLabel();
        opCancelLoc = new javax.swing.JButton();
        bdBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        ipFieldRem = new javax.swing.JTextField();
        opPassRem = new javax.swing.JLabel();
        opUserRem = new javax.swing.JLabel();
        bdBoxRem = new javax.swing.JComboBox();
        opIPRem = new javax.swing.JLabel();
        opSaveRem = new javax.swing.JButton();
        loginFieldRem = new javax.swing.JTextField();
        senhaFieldRem = new javax.swing.JTextField();
        opNameRem = new javax.swing.JLabel();
        nameFieldRem = new javax.swing.JTextField();
        opBDRem = new javax.swing.JLabel();
        opCancelRem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setTitle("Preferencias");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Preferências"); // NOI18N

        opPassLoc.setText("Senha");

        opIPLoc.setText("     IP");

        opUserLoc.setText("Login");

        opSaveLoc.setText("Salvar");
        opSaveLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSaveLocActionPerformed(evt);
            }
        });

        opNameLoc.setText("Nome");

        opBDLoc.setText("Banco de Dados");

        opCancelLoc.setText("Cancel");
        opCancelLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opCancelLocMouseClicked(evt);
            }
        });
        opCancelLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCancelLocActionPerformed(evt);
            }
        });

        bdBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MYSQL", "HSQLBD" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(opBDLoc)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(opIPLoc)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(opPassLoc)
                                        .addGap(22, 22, 22))
                                    .addComponent(senhaField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(opSaveLoc)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(opNameLoc)))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loginField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(opUserLoc)
                                            .addGap(22, 22, 22)))
                                    .addComponent(opCancelLoc))))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(opBDLoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(opNameLoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(opUserLoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opPassLoc)
                            .addComponent(opIPLoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opSaveLoc)
                    .addComponent(opCancelLoc))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Local", jPanel1);

        opPassRem.setText("Senha");

        opUserRem.setText("Login");

        bdBoxRem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MYSQL", "HSQLBD" }));

        opIPRem.setText("     IP");

        opSaveRem.setText("Salvar");
        opSaveRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSaveRemActionPerformed(evt);
            }
        });

        opNameRem.setText("Nome");

        opBDRem.setText("Banco de Dados");

        opCancelRem.setText("Cancel");
        opCancelRem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opCancelRemMouseClicked(evt);
            }
        });
        opCancelRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCancelRemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(opBDRem)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(opSaveRem)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(opNameRem))
                                    .addComponent(ipFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(opIPRem)))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginFieldRem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(opUserRem)
                                        .addGap(22, 22, 22)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(opPassRem)
                                        .addGap(22, 22, 22))
                                    .addComponent(senhaFieldRem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(opCancelRem))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bdBoxRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(opBDRem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdBoxRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(opUserRem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opPassRem))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(opNameRem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(opIPRem)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ipFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(senhaFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opSaveRem)
                    .addComponent(opCancelRem))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remoto", jPanel2);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void opCancelLocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opCancelLocMouseClicked
    this.setVisible(false);
  }//GEN-LAST:event_opCancelLocMouseClicked

  private void opSaveLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSaveLocActionPerformed

    ip = ipField.getText();
    login = loginField.getText();
    senha = senhaField.getText();
    bd = bdBox.getSelectedIndex();
    name = nameField.getText();

    save("preferences.txt");     // Save the Prferencess

    if(flag)
    try {
      DataBase dbPrincipal = DataBase.getDbL("preferences.txt");
      flag = dbPrincipal.create(bd ,ip ,login ,senha ,name);
    } catch (SQLException QWERTY) {
      JOptionPane.showMessageDialog(null, "Wrong Login or Passord");
    } catch (IOException QWERTY) {
      JOptionPane.showMessageDialog(null, "Wrong Login or Password");
    }
    setVisible(false);
    
    //this.setVisible(false);
  }//GEN-LAST:event_opSaveLocActionPerformed

  private void opSaveRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSaveRemActionPerformed

    ip = ipFieldRem.getText();
    login = loginFieldRem.getText();
    senha = senhaFieldRem.getText();
    bd = bdBoxRem.getSelectedIndex();
    name = nameFieldRem.getText();

    save("remote.txt");     // Save the Prferencess

    if(flag)try {
      DataBase dbPrincipal = DataBase.getDbR("remote.txt");
      flag = dbPrincipal.create(bd ,ip ,login ,senha ,name);
    } catch (SQLException QWERTY) {
      JOptionPane.showMessageDialog(null, "Wrong Login or Passord");
    } catch (IOException QWERTY) {
      JOptionPane.showMessageDialog(null, "Wrong Login or Password");
    }
    
    setVisible(false);
  }//GEN-LAST:event_opSaveRemActionPerformed

  private void opCancelRemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opCancelRemMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_opCancelRemMouseClicked

    private void opCancelRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCancelRemActionPerformed
       setVisible(false);
    }//GEN-LAST:event_opCancelRemActionPerformed

    private void opCancelLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCancelLocActionPerformed
        setVisible(false);
    }//GEN-LAST:event_opCancelLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              try {
                new Preferencias().setVisible(true);
              } catch (FileNotFoundException ex) {
                Logger.getLogger(Preferencias.class.getName()).log(Level.SEVERE, null, ex);
              } catch (IOException ex) {
                Logger.getLogger(Preferencias.class.getName()).log(Level.SEVERE, null, ex);
              }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bdBox;
    private javax.swing.JComboBox bdBoxRem;
    private javax.swing.JTextField ipField;
    private javax.swing.JTextField ipFieldRem;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField loginField;
    private javax.swing.JTextField loginFieldRem;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameFieldRem;
    private javax.swing.JLabel opBDLoc;
    private javax.swing.JLabel opBDRem;
    private javax.swing.JButton opCancelLoc;
    private javax.swing.JButton opCancelRem;
    private javax.swing.JLabel opIPLoc;
    private javax.swing.JLabel opIPRem;
    private javax.swing.JLabel opNameLoc;
    private javax.swing.JLabel opNameRem;
    private javax.swing.JLabel opPassLoc;
    private javax.swing.JLabel opPassRem;
    private javax.swing.JButton opSaveLoc;
    private javax.swing.JButton opSaveRem;
    private javax.swing.JLabel opUserLoc;
    private javax.swing.JLabel opUserRem;
    private javax.swing.JTextField senhaField;
    private javax.swing.JTextField senhaFieldRem;
    // End of variables declaration//GEN-END:variables

  private void load(String file) throws FileNotFoundException, IOException{
    BufferedReader br = null;                   // READ
    String sCurrentLine;
    String[] ans = new String[5];
    int i = 0;

    br = new BufferedReader(new FileReader(new File(file)));            //// start copy first part of Index
    while ((sCurrentLine = br.readLine()) != null) {
          ans[i] = sCurrentLine;  
          i++;
    }
    bd = Integer.parseInt(ans[0]);
    name = ans[1];
    ip = ans[2];
    login =  ans[3];
    senha =  ans[4];
  }
  
  private void loadLoc() throws IOException{
        load("preferences.txt");
        bdBox.setSelectedIndex(bd);
        nameField.setText(name);
        ipField.setText(ip);        
        loginField.setText(login);
        senhaField.setText(senha);
  }
  
  private void loadRem() throws IOException{
        load("remote.txt");
        bdBoxRem.setSelectedIndex(bd);
        nameFieldRem.setText(name);
        ipFieldRem.setText(ip);        
        loginFieldRem.setText(login);
        senhaFieldRem.setText(senha);
  }
  
  private void save(String file){
    try {
      FileWriter fstream = null;
      fstream = new FileWriter(file); //WRITE
      BufferedWriter out = new BufferedWriter(fstream); 

      out.write(String.valueOf(bd));
      out.newLine();
      out.write(name);
      out.newLine();
      out.write(ip);
      out.newLine();
      out.write(login);
      out.newLine();
      out.write(senha);

      out.close();

     // System.out.println("IP  "+ip+" - "+"Login "+login+" - "+" Senha "+senha+" - "+" bd "+bd);
    } catch (IOException ex) {
        Logger.getLogger(Preferencias.class.getName()).log(Level.SEVERE, null, ex);
    }
  }
  public void translate() throws FileNotFoundException, IOException{
    Vector<String> aux = utilsIO.getTranslate("opName opIP opUser opPass bCreate opSave opCancel opBD");
      
    opNameLoc.setText(aux.get(0));
    opNameRem.setText(aux.get(0));
    
    opIPLoc.setText(aux.get(1));
    opIPRem.setText(aux.get(1));
    
    opUserLoc.setText(aux.get(2));
    opUserRem.setText(aux.get(2));
    
    opPassLoc.setText(aux.get(3));
    opPassRem.setText(aux.get(3));

    if(flag){
      opSaveLoc.setText(aux.get(4));
      opSaveRem.setText(aux.get(4));
    }
    else{
      opSaveLoc.setText(aux.get(5));
      opSaveRem.setText(aux.get(5));
    }
    opCancelLoc.setText(aux.get(6));
    opCancelRem.setText(aux.get(6));
    
    opBDLoc.setText(aux.get(7));
    opBDRem.setText(aux.get(7));
  }


  public int getBd() {
    return bd;
  }

  public String getIp() {
    return ip;
  }
  
}
