/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Brawan
 */
public class Search extends javax.swing.JFrame {
String pesquisador = "";
String area = "" ;
String subArea = "";
String producao = "";
int anoL = 0,anoH = 99999999;

/**
     * Creates new form NewJFrame
     */
    public Search() throws FileNotFoundException, IOException {
        initComponents();
        translate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cSearch = new javax.swing.JButton();
    cCancel = new javax.swing.JButton();
    pChave = new javax.swing.JTextField();
    cKey = new javax.swing.JLabel();
    cPesq = new javax.swing.JCheckBox();
    cProd = new javax.swing.JCheckBox();
    cSubA = new javax.swing.JCheckBox();
    cArea = new javax.swing.JCheckBox();
    anoLow = new javax.swing.JTextField();
    anoHigh = new javax.swing.JTextField();
    cYear = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setTitle("Pesquisar");

    cSearch.setText("Buscar");
    cSearch.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        cSearchMouseClicked(evt);
      }
    });
    cSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cSearchActionPerformed(evt);
      }
    });

    cCancel.setText("Cancel");
    cCancel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        cCancelMouseClicked(evt);
      }
    });
    cCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cCancelActionPerformed(evt);
      }
    });

    pChave.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        pChaveActionPerformed(evt);
      }
    });

    cKey.setText("Palavras Chaves");

    cPesq.setText(" Pesquisador");

    cProd.setText("Produção");

    cSubA.setText("Sub Área de Atuação");

    cArea.setText("Área de Atuação");

    anoHigh.setName(""); // NOI18N

    cYear.setText("Ano de Produção");

    jLabel2.setText("-");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cKey)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(pChave, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addComponent(cSearch)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cCancel)
        .addGap(55, 55, 55))
      .addGroup(layout.createSequentialGroup()
        .addGap(60, 60, 60)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(anoLow, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel2)
            .addGap(18, 18, 18)
            .addComponent(anoHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(44, 44, 44)
            .addComponent(cYear))
          .addGroup(layout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cArea)
              .addComponent(cSubA)
              .addComponent(cProd)
              .addComponent(cPesq))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(pChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cKey))
        .addGap(18, 18, 18)
        .addComponent(cPesq)
        .addGap(18, 18, 18)
        .addComponent(cProd)
        .addGap(18, 18, 18)
        .addComponent(cArea)
        .addGap(14, 14, 14)
        .addComponent(cSubA)
        .addGap(18, 18, 18)
        .addComponent(cYear)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(anoHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(anoLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(35, 35, 35)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cSearch)
          .addComponent(cCancel))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void cSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSearchActionPerformed
       
    }//GEN-LAST:event_cSearchActionPerformed

    private void cSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cSearchMouseClicked
        String str = "";
        String aux = "";
        
        str =  anoLow.getText();
        if(str.length() > 0)
            anoL = Integer.parseInt(str);
        str =  anoHigh.getText();
        if(str.length() > 0)
            anoH = Integer.parseInt(str);
        
        str = pChave.getText();             
        
        if(cPesq.isSelected()){
            aux = str.replaceAll(" ", "%' or p.nome like '%");
            pesquisador = " and (p.nome like '%"+aux+"%' ) ";
        }
        if(cProd.isSelected()){
            aux = str.replaceAll(" ", "%' or j.nome like '%");
            producao = " and (j.nome like '%"+aux+"%' ) ";
        }
        if(cArea.isSelected()){
            aux = str.replaceAll(" ", "%' or p.area like '%");
            area = " and (p.area like '%"+aux+"%' ) ";
        }
        if(cSubA.isSelected()){
            aux = str.replaceAll(" ", "%' or p.subarea like '%");
            subArea = " and (p.subarea like '%"+aux+"%' ) ";
        }
        
        try {
            Busca init = new Busca(pesquisador,producao,area,subArea,anoL,anoH);
        } catch (SQLException ex) {
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
    }//GEN-LAST:event_cSearchMouseClicked

    private void cCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCancelMouseClicked
       setVisible(false);
    }//GEN-LAST:event_cCancelMouseClicked

    private void pChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pChaveActionPerformed

  private void cCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCancelActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cCancelActionPerformed
   
    public void translate() throws FileNotFoundException, IOException{
      Locale currentLocale;
      ResourceBundle messages;

      BufferedReader br = null;                   // READ
      String sCurrentLine;
      String local = "";
      int i = 0;


        br = new BufferedReader(new FileReader("locale.txt"));            //// start copy first part of Index
        while ((sCurrentLine = br.readLine()) != null) {
              local = sCurrentLine;  
        }

      if(local.equals("pt_BR"))
        currentLocale = new Locale("en","US");
      else
        currentLocale = new Locale("pt","BR");

      messages = ResourceBundle.getBundle("locales.MessagesBundle",currentLocale);
  
      cPesq.setText(messages.getString("cPesq"));
      cProd.setText(messages.getString("cProd"));
      cArea.setText(messages.getString("cArea"));
      cSubA.setText(messages.getString("cSubA"));

      cKey.setText(messages.getString("cKey"));
      cYear.setText(messages.getString("cYear"));
      cSearch.setText(messages.getString("cSearch"));
      cCancel.setText(messages.getString("cCancel"));
      this.setTitle(messages.getString("cTitle"));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              try {
                new Search().setVisible(true);
              } catch (FileNotFoundException ex) {
                Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
              } catch (IOException ex) {
                Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
              }
            }
        });
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField anoHigh;
  private javax.swing.JTextField anoLow;
  private javax.swing.JCheckBox cArea;
  private javax.swing.JButton cCancel;
  private javax.swing.JLabel cKey;
  private javax.swing.JCheckBox cPesq;
  private javax.swing.JCheckBox cProd;
  private javax.swing.JButton cSearch;
  private javax.swing.JCheckBox cSubA;
  private javax.swing.JLabel cYear;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField pChave;
  // End of variables declaration//GEN-END:variables
}
