/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Victor
 */
public class UpdateScreen extends javax.swing.JFrame {

    /**
     * Creates new form UpdateScreen
     */
    public UpdateScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localButton = new javax.swing.JButton();
        remoteButton = new javax.swing.JButton();

        localButton.setText("Local");
        localButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localButtonActionPerformed(evt);
            }
        });

        remoteButton.setText("Remoto");
        remoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remoteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remoteButton)
                    .addComponent(localButton))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(localButton)
                .addGap(26, 26, 26)
                .addComponent(remoteButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localButtonActionPerformed
       File dir = null;
       javax.swing.JFileChooser jFileChooser  = new JFileChooser(); 
       jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
       int opcao = jFileChooser.showOpenDialog(this);
      
       if (opcao == JFileChooser.APPROVE_OPTION){
        dir = jFileChooser.getSelectedFile();
       }
                  
       if(dir!= null){  
            try {               
               UpdateBD init = new UpdateBD(dir.getAbsolutePath(),true);
           } catch (IOException ex) {
               Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
           } catch (InterruptedException ex) {
               Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
           } catch (Exception ex) {   
           Logger.getLogger(InterfaceBD.class.getName()).log(Level.SEVERE, null, ex);
         }   
       }
       setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_localButtonActionPerformed

    private void remoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remoteButtonActionPerformed
 
      try {               
           UpdateBD init = new UpdateBD(null,false);
        } catch (IOException ex) {
            Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(CurrLattes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {   
        Logger.getLogger(InterfaceBD.class.getName()).log(Level.SEVERE, null, ex);
      } 
      setVisible(false);
    }//GEN-LAST:event_remoteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton localButton;
    private javax.swing.JButton remoteButton;
    // End of variables declaration//GEN-END:variables
}
